import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/NextUiProvider";
import { Toaster } from "@/components/ui/sonner";
import { validateRequest } from "@/lib/lucia/auth";
import { SessionProvider } from "@/provider/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sessionData = await validateRequest();

  return (
    <html lang="en" className="h-full">
      <body className={"h-full m-0 p-0 " + inter.className}>
        <Provider>
          <SessionProvider value={sessionData}>{children}</SessionProvider>
        </Provider>

        <Toaster richColors />
      </body>
    </html>
  );
}
